### PR TITLE
Fixes for issues #24, #25, and #26.

### PR DESCRIPTION
**Pull request by jtlapp**
Fixes for issues #24, #25, and #26, in support of the [`gifwrap`](https://github.com/jtlapp/gifwrap) library.

Also, should you be interested, and I can push working [Typescript typings for `omggif`](https://github.com/jtlapp/gifwrap/blob/master/src/omggif.d.ts).

### CODE REVIEW

**Comment by deanm** [comment]
Throwing Errors instead of strings in d0e308f1a84e3dd9d4201fb88971bb7ac414dbc1

**Comment by deanm** [comment]
Block size issue should throw an exception 704ae9335d8088aa51fc89e63e1ed66ceeefd173

That should be all of it, thanks again!

**Comment by jtlapp** [comment]
Looks like I'd need this, because `end()` needs to write another byte...

```js
g = new GifWriter(buf, ...)
p = g.addFrame(...)
if (p >= buf.length - 1) {
  // The buffer we supplied wasn't big enough, we have to do something about it here
}
```

**Comment by deanm** [comment]
Well it depends if you plan to add more frames.  end() also returns p, so as I wrote in the commit message, the best practice would be to check both the result of any addFrame() calls, and the result of end().

**Pull request closed without merging**
