### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by annelu**
Adding the MIT license to package.json and the LICENSE file enable license validation

### CODE REVIEW

**Comment by bclinkinbeard** [comment]
Is there an ETA for merging and republishing? Thanks!

**Comment by deanm** [comment]
I don't see a problem adding the mit license property to the package.json, but the license text is already in the code (and README, which I only added for github's display), does it doesn't really make any sense to triplicate the license text for a project that is only a single file.

**Comment by ljharb** [comment]
Please do add and publish the package.json declaration, at least - it’s how we programmatically verify dependency licenses.

**Comment by deanm** [comment]
334a0c0b6aa2eb5e63fae64ba7911ee647655ab2

and published npm 1.0.10 specifying MIT license:

https://www.npmjs.com/package/omggif

**Pull request closed without merging**
